### ISSUE TITLE
Password via Javascript...

### ISSUE THREAD

**Issue by demobiel** [seedcode/fmxj#2]
Hi,

First of all, great job, this is a nice and straight forward implementation of the FileMaker XML engine.

One small remark (something I struggle with as well to find the best way to manage this), is:  I think it is a bit dangerous to manage the database access from within the javascript code. I would move that part to the PHP side.

Kind regards

Andries

**Comment by JasonChrYoung** [comment]
Hi Andries,

Thank you for looking and posting!

Yes, we agree. Using the phpRelay file is the secure way to go, even if you are hosting the JavaScript on the server itself.  For folks who are using the Guest account for a public site, then it's probably OK to do the httpPost right to the server.  Otherwise, as I understand it, even if the server is secure, it still always uses basic auth. I describe this in the docs, because it is how FMS handles it, but I should probably be a little more "discouraging" of this method.

For our demo, we just have our xml account info hardcoded into the phpRelay file to do the log-in.

We did set it up so you can pass a u and p property with the phpRelay object.  They will be sent as part of the POST payload to the php file.  The phpRelay file will then parse those off the payload and use them to authenticate to the server before doing it's curl POST to the server. If both the JavaScript and FMS are hosted on secure servers then, as I understand it, this is OK if those values are coming from a secure form.

Please let us know if that sounds right, and if you have any suggestions on making this more clear. As you point out it's a struggle!

Thanks,
Jason
