### ISSUE TITLE
nested portal error

### ISSUE THREAD

**Issue by pacific707** [seedcode/fmxj#3]
so I was getting an error if the portal I was trying to next was empty.

I just added if (row.getElementsByTagName(colTag)[i]) to the function valueByIndex(i) that just skips the function if the portal has no records.  Not sure if there was a better way but It appears to have done the job.  Maybe It would be better to remove the whole parent element?

**Comment by JasonChrYoung** [comment]
Right, that fix sounds good. I'll run through it a bit and see about removing the parent.
Thanks!!

**Comment by JasonChrYoung** [comment]
Hi,

I'm inclined to leave the property, **i.e. -ContactInfo** with  a value of "", as someone would need to test for the property existence for each object to avoid an error. I think knowing the property is in the object if it's corresponding object is on the layout is a little more robust.
I'll push a fix up soon, but it's similar to yours. If that sounds good, I'll close this when the fix is pushed.

Thanks so much!!!

``` javascript
function valueByIndex(i){
    //Just get the values by index
    //return as an array as we may have multiples.
    var column = row.getElementsByTagName(colTag)[i];
    //if there are no elements, the portal is empty, return empty string
    if(!column){
        return ""
    }
...
```

``` javascript
function arraysToObjects(index, arrays){
    var result = [];
    var aLgth = arrays[0].length;
    // if the passed arrays are empty then return an empty string
    if(aLgth===0){
               return "";
    }
...
```

**Comment by pacific707** [comment]
this introduced a couple of interesting errors.
1. If there is a related field on the layout it puts each char as a value in a chile object.
2. If you have 2 portals on 1 layout the items are duplicated in the other related object.

**Comment by pacific707** [comment]
it appears these may be separate issues
